# Generated by Django 3.1.3 on 2022-01-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='phote',
            new_name='photo',
        ),
    ]
